### ISSUE TITLE
Issue with setgpu.py

### ISSUE THREAD

**Issue by davo** [sinatv52/BlenderOnColab#1]
Hey friend, thanks for keeping this notebook up to date.

I've been using a similar notebook for almost a month without the setgpu.py trick.

Unfortunately I keep running on an issue when running blender with the `setgpu.py` script. Here is what I get out on the terminal.
```
Blender 3.0.0 Alpha (hash 7d5e8d2bc149 built 2021-08-30 02:51:40)
Traceback (most recent call last):
  File "/content/setgpu.py", line 6, in <module>
    prefs.addons['cycles'].preferences.get_devices()
  File "/content/blender-3.0.0-alpha+cycles-x.7d5e8d2bc149-linux.x86_64-release/3.0/scripts/addons/cycles/properties.py", line 1329, in get_devices
    self.refresh_devices()
  File "/content/blender-3.0.0-alpha+cycles-x.7d5e8d2bc149-linux.x86_64-release/3.0/scripts/addons/cycles/properties.py", line 1325, in refresh_devices
    self.update_device_entries(_cycles.available_devices(device_type))
ValueError: Device "OPENCL" not known.
Read blend: /gdrive/MyDrive/Blender/primitives_02.blend
```

Notice the `ValueError: Device "OPENCL" not known.`. Blender keeps running and I get a render out of the notebook, but it seems that is not using the GPU.

For more context, I'm using Google Colab Pro+ and I followed your advice to restart the notebook in order to get a `P100`.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Any advice? Thanks!

**Comment by sinaasadiyan** [comment]
hey,
currently i do not have any idea about that, i keep this issue open if somebody came with a solution.
I use the free version of Coab, but did not face any problem even when i could access the P100. 
Just assure that the Edit -> Preferences -> System be set on cuda.
and try the stable versions of colab (not 3.0.0)

**Comment by sinaasadiyan** [comment]
Just tested Blender 3.0 with cycles X, use the following line without setgpu.py, that was really fast. but testing with K80, hope there is no problem with p100 either :
`!sudo ./blender/blender  -b '/content/sina2.blend' -noaudio -E 'CYCLES' -o '/content/sina' -s 28 -e 50 -a -- --cycles-device CUDA`

**Comment by sinaasadiyan** [comment]
Notebook Updated in 2022/03/10, and works properly.
so i close this issue.
